/* Style reminder: Research IDE — galerie de fichiers consultables, téléchargeables et clairement séparés des pièces privées. */
import { ArchiveIcon, Download, Eye, Filter, ImageOff, RotateCcw, RotateCw } from "lucide-react";
import { useMemo, useState } from "react";
import { Locale, SectionId } from "@/lib/archiveData";
import { PublicEvidence } from "@/lib/publicEvidence";
import { localeTools } from "@/lib/translation";

const copy: Record<Locale, { title: string; lead: string; download: string; empty: string; year: string; type: string; organization: string; all: string; reset: string; result: string; redressed: string; yearGroup: string }> = {
  fr:{ title:"Fichiers visualisables", lead:"Aperçus et fichiers téléchargeables autorisés dans cette section.", download:"Télécharger", empty:"Aucun fichier public téléchargeable n’est disponible dans cette section. Les notices restent consultables ci-dessous.", year:"Année", type:"Type", organization:"Organisme", all:"Tous", reset:"Réinitialiser", result:"résultat(s)", redressed:"Aperçu public redressé", yearGroup:"Registre annuel" },
  en:{ title:"Viewable files", lead:"Authorised previews and downloadable files in this section.", download:"Download", empty:"No public downloadable file is available in this section. Records remain available below.", year:"Year", type:"Type", organization:"Organisation", all:"All", reset:"Reset", result:"result(s)", redressed:"Corrected public preview", yearGroup:"Annual register" },
  ar:{ title:"ملفات قابلة للعرض", lead:"معاينات وملفات مسموح بتنزيلها في هذا القسم.", download:"تنزيل", empty:"لا يوجد ملف عام قابل للتنزيل في هذا القسم. تبقى البطاقات متاحة أدناه.", year:"السنة", type:"النوع", organization:"الجهة", all:"الكل", reset:"إعادة", result:"نتيجة", redressed:"معاينة عامة مصححة الاتجاه", yearGroup:"السجل السنوي" },
  es:{ title:"Archivos visualizables", lead:"Vistas previas y archivos descargables autorizados en esta sección.", download:"Descargar", empty:"No hay un archivo público descargable en esta sección. Las fichas siguen disponibles abajo.", year:"Año", type:"Tipo", organization:"Organización", all:"Todos", reset:"Restablecer", result:"resultado(s)", redressed:"Vista pública corregida", yearGroup:"Registro anual" },
  nl:{ title:"Bekijkbare bestanden", lead:"Toegestane previews en downloads in deze sectie.", download:"Downloaden", empty:"Er is geen openbaar downloadbaar bestand in deze sectie.", year:"Jaar", type:"Type", organization:"Organisatie", all:"Alle", reset:"Herstellen", result:"resultaat/resultaten", redressed:"Gecorrigeerde openbare preview", yearGroup:"Jaarregister" },
  de:{ title:"Anzeigbare Dateien", lead:"Autorisierte Vorschauen und Downloads in diesem Bereich.", download:"Herunterladen", empty:"In diesem Bereich ist keine öffentliche Datei zum Herunterladen verfügbar.", year:"Jahr", type:"Typ", organization:"Organisation", all:"Alle", reset:"Zurücksetzen", result:"Ergebnis(se)", redressed:"Korrigierte öffentliche Vorschau", yearGroup:"Jahresregister" },
};

export default function EvidenceGallery({ section, locale, evidence, onPreview }: { section: SectionId; locale: Locale; evidence: PublicEvidence[]; onPreview: (item: PublicEvidence, collection: PublicEvidence[]) => void }) {
  const t = copy[locale];
  const globalArchive = "/manus-storage/cherki-el-mehdi-public-dossier_24f4ace8.zip";
  const [year, setYear] = useState("all");
  const [type, setType] = useState("all");
  const [organization, setOrganization] = useState("all");
  const years = useMemo(() => Array.from(new Set(evidence.map(item => item.year))).sort().reverse(), [evidence]);
  const types = useMemo(() => Array.from(new Set(evidence.map(item => item.type))).sort(), [evidence]);
  const organizations = useMemo(() => Array.from(new Set(evidence.map(item => item.organization))).sort(), [evidence]);
  const filtered = useMemo(() => evidence.filter(item => (year === "all" || item.year === year) && (type === "all" || item.type === type) && (organization === "all" || item.organization === organization)), [evidence, year, type, organization]);
  const yearGroups = useMemo(() => Array.from(new Set(filtered.map(item => item.year))).sort((a, b) => { const aYear = Number(a.match(/\d{4}/)?.[0] || 0); const bYear = Number(b.match(/\d{4}/)?.[0] || 0); return bYear - aYear || a.localeCompare(b); }).map(value => ({ year:value, items:filtered.filter(item => item.year === value) })), [filtered]);
  if (!evidence.length) return <section className="evidence-gallery evidence-empty"><ImageOff size={19} /><div><span>public-assets/{section}</span><p>{t.empty}</p></div></section>;
  const reset = () => { setYear("all"); setType("all"); setOrganization("all"); };
  const grid = (items: PublicEvidence[]) => <div className="evidence-grid">{items.map(item => <article key={item.id}><button className="evidence-thumb" onClick={() => onPreview(item, filtered)}><img src={item.preview} alt={`Aperçu : ${item.title}`} /><span><Eye size={14} /> PREVIEW</span></button><div className="evidence-meta"><span>{item.id}</span><h3>{item.title}</h3><p>{item.source}</p>{item.previewRedressed && <p className="preview-redressed"><RotateCw size={12} /> {t.redressed}</p>}{item.curriculum && <div className="curriculum-summary"><b>MODULES / MATIÈRES</b>{item.curriculum.map(value => <span key={value}>{value}</span>)}</div>}<div className="evidence-tags"><i>{item.year}</i><i>{item.type}</i><i>{item.organization}</i></div></div><footer><button onClick={() => onPreview(item, filtered)}><Eye size={14} /> {localeTools[locale].preview}</button><a href={item.download} download><Download size={14} /> {t.download}</a></footer></article>)}</div>;
  return <section className="evidence-gallery"><header><div><span>public-assets/{section}</span><h2>{t.title}</h2><p>{t.lead}</p></div><div className="evidence-header-actions"><b>{filtered.length.toString().padStart(2,"0")}</b>{section === "registry" && <a className="registry-export" href={globalArchive} download><ArchiveIcon size={15} /> {locale === "fr" ? "Télécharger l’archive ZIP complète" : "Download complete ZIP archive"}</a>}</div></header><div className="evidence-filters"><div className="filter-title"><Filter size={15} /><span>filter.query</span></div><label>{t.year}<select value={year} onChange={event => setYear(event.target.value)}><option value="all">{t.all}</option>{years.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>{t.type}<select value={type} onChange={event => setType(event.target.value)}><option value="all">{t.all}</option>{types.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>{t.organization}<select value={organization} onChange={event => setOrganization(event.target.value)}><option value="all">{t.all}</option>{organizations.map(value => <option key={value} value={value}>{value}</option>)}</select></label><button onClick={reset}><RotateCcw size={13} /> {t.reset}</button><p>{filtered.length} {t.result}</p></div>{section === "registry" ? <div className="evidence-year-groups">{yearGroups.map(group => <section className="evidence-year-group" key={group.year}><header><span>{t.yearGroup}</span><h3>{group.year}</h3><b>{group.items.length.toString().padStart(2,"0")}</b></header>{grid(group.items)}</section>)}</div> : grid(filtered)}{!filtered.length && <p className="evidence-no-result">0 // {t.result}</p>}</section>;
}
